More efficient mechanism for fetching/batching orders in the control panel
jazkarta/jazkarta.shop pull request #77
Opened 2022-03-12 23:32 UTC by alecpm

The prior implementation retrieved all orders and then sorted them before filtering them by date. This implementation retrieves only the keys (which include a date), filters and sorts those keys, and then provides a lazy list implementation for retrieving the order items which can be used for batching.

This will also require some changes to [jazkarta.pfg.jazshop](https://github.com/jazkarta/jazkarta.pfg.jazshop) which imports and uses the private `_fetch_orders()` function.

2022-03-12 23:33 UTC, alecpm commented
This also incorporates the pick-a-date date picker switch from issue #70 (PR #75)

2022-03-12 23:48 UTC, alecpm commented
See jazkarta/jazkarta.pfg.jazshop#2 for related updates to that package.

2022-03-16 17:16 UTC, fulv requested changes
I get a 404 when I try loading @@jazkarta-shop-orders now.

2022-03-16 17:35 UTC, alecpm commented
@fulv Is that happening on your local instance when using this branch?

2022-03-16 22:48 UTC, alecpm commented
@fulv I've fixed the issue causing the 404. For some reason on NCI `view/__name__` was throwing an attribute error. That's not a change that I introduced, but it may have been added on master at some point. It was also breaking the shipping control panel, but it should be working now.

I've deployed the changes to staging and it seems to be performing quite well there.

2022-03-16 22:51 UTC, alecpm commented
Oddly, I didn't see that `view/__name__` issue when testing on my local copy of NCI staging (just pulled this morning), but it did happen on staging. Very strange.

2022-03-17 17:17 UTC, jessesnyder commented
Order filtering & speed, and CSV download all working well for me now.

2022-03-21 18:20 UTC, merged